# Generated by Django 5.0.6 on 2024-07-30 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_businessmonth_margin'),
        ('drugs', '0021_alter_drug_day_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.drug'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='drugs.drug'),
        ),
    ]
