# Generated by Django 5.0.6 on 2024-07-20 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='_drug_name')),
                ('brand_name', models.CharField(max_length=30)),
                ('mass', models.CharField(max_length=10)),
                ('state', models.CharField(choices=[('Tab', 'Tab'), ('Suspension', 'Suspension'), ('Injectable', 'Injectable')], default='Tablet', max_length=10)),
                ('manufacturer', models.CharField(max_length=30)),
                ('exp_date', models.DateField(verbose_name='_expiery_date')),
                ('stock_amount', models.IntegerField()),
                ('purchase_amount', models.IntegerField()),
                ('purchase_units', models.CharField(choices=[('Cartons', 'Cartons'), ('Packets', 'Packets'), ('Unit', 'Sachets/Bottle/Card')], default='Unit', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=30)),
                ('purpose', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('day_added', models.DateField(default='2024-07-20')),
                ('oos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Injectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Suspension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_bottles', models.IntegerField()),
                ('no_packs', models.IntegerField(default=1, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
        migrations.CreateModel(
            name='Tablet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_tab', models.CharField(max_length=10, null=True)),
                ('no_packs', models.IntegerField(default=0, null=True)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drugs.drug')),
            ],
        ),
    ]
