# Generated by Django 5.0.6 on 2024-07-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(default='2024-07-21'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='exp_date',
            field=models.DateField(verbose_name='Expiery Date'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='drug',
            name='stock_amount',
            field=models.IntegerField(null=True),
        ),
    ]
