# Generated by Django 5.0.6 on 2024-07-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_alter_drug_day_added_alter_drug_exp_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
