# Generated by Django 5.0.6 on 2024-07-23 19:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0005_alter_drug_day_added_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
