# Generated by Django 5.0.6 on 2024-07-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0006_alter_sale_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(default='<built-in method date of datetime.datetime object at 0x792a3e6cb180>'),
        ),
    ]
