# Generated by Django 5.0.6 on 2024-07-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0008_alter_drug_day_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='oos',
        ),
    ]
