# Generated by Django 5.0.6 on 2024-07-25 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0011_suspension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='time',
        ),
    ]
