# Generated by Django 5.0.6 on 2024-07-25 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0012_remove_sale_amount_remove_sale_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
