# Generated by Django 5.0.6 on 2024-07-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0014_alter_suspension_no_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectible',
            name='drug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drugs.drug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(default='2024-07-26'),
        ),
    ]
