# Generated by Django 5.0.6 on 2024-07-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0015_injectible_drug_alter_drug_day_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='injectible',
            name='no_packs',
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name='injectible',
            name='no_viles',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
