# Generated by Django 5.0.6 on 2024-07-26 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0016_injectible_no_packs_injectible_no_viles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sale',
        ),
    ]
