# Generated by Django 5.0.6 on 2024-07-29 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0019_rename_injectible_injectable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug',
            name='day_added',
            field=models.DateField(default='2024-07-29'),
        ),
    ]
